version: "3.9"
services:

  backend:
    build:
      context: app
    volumes:
      - ./app:/opt/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      ENVIRONMENT: LOCAL

  postgres:
    image: postgres:15.5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/create-content-schema.sh:/docker-entrypoint-initdb.d/create-content-schema.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 1s
      timeout: 2s
      retries: 5
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

networks:
  default:
      name: movies
