name: Проверка
on: [push]
jobs:
  flake8:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'
    - name: Install dependencies
      run: |
        pip install flake8==6.1.0 wemake-python-styleguide==0.18.0 flake8-bandit==4.1.1 bandit==1.7.5
    - name: Run flake8 & mypy
      run: |
        cd django_api && flake8 .
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'
    - name: Install dependencies
      run: |
        pip install pytest==7.4.3
    - name: Run tests
      run: |
        echo "Success!"
